{% set version = "0.9" %}

package:
  name: otmorris
  version: {{ version }}

source:
  fn: otmorris-{{ version }}.tar.gz
  url: https://github.com/openturns/otmorris/archive/v{{ version }}.tar.gz
  sha256: b74519f29e5ef7c639d859ccba70c1bc67b7693749ebcae7326c6e248bfeff63

build:
  number: 2
  run_exports:
    - {{ pin_subpackage('otmorris', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - swig
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - curl  # [win]
  host:
    - python
    - openturns 1.16*
  run:
    - python
    - openturns 1.16*

test:
  imports:
    - otmorris

about:
  home: http://openturns.org/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: Morris screening module

extra:
  recipe-maintainers:
    - jschueller
