{% set version = "0.8" %}

package:
  name: otmorris
  version: {{ version }}

source:
  fn: otmorris-{{ version }}.tar.gz
  url: https://github.com/openturns/otmorris/archive/v{{ version }}.tar.gz
  sha256: 2c80fbfe5518eaee668c4d3f1157242f32181cd2254b4e6ab950db9f5716e811

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('otmorris', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - swig
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - openturns
  run:
    - python
    - openturns

test:
  imports:
    - otmorris

about:
  home: http://openturns.org/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: Morris screening module

extra:
  recipe-maintainers:
    - jschueller
