appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: AhJXutB90lAeTaPblCjYVuy52+JaOIpDi+bUn7Lf1RiboPn8Bfoc5BM2wY+UMRIR61PsW0OqrR4/kiMIpEEJhxztXDYfUveca/DsJ/xaHHfStFSsTq+PgoVxTvGvjInCT4dd1qIr5i9XfYqirnlDZVpbOTrPdnmaFZEeASpgG8LNF47xdfBKgoT3FlvzM6czwb+2QWzvyWzQGl1aOpoIzafK+APnf//Wyjem2fbGX0kkaxJ/P2iJQhd2KI8kIXChgxDDXgQXutlHDvusyPZB9+FVK9iZs9uPN1/JStWl5BsxDGc0iDc+BqoYpZAL7BWAz7CxOnpIDvZz1otQIJj9BAiBQ4AMcS/bnpm70SJVRsRZu8x3Ddj21/0jQmaXynNaqXTvAx1n17UeRD+l/TAkq/ZSEVWYvs0k7EmDsn0s4pMJmUX/PabQH5SSkynSwyUhaiIHkrTWPpfdb9WhjfDqDNpFkXdFDwNoVQBJPLYYpf+5BTlpM+351CAMeZE9FU3SoBnjZvuYUEMzLaPZlZ5rvlThjfgsbKGCujqExZ3bT5mVFvnGrXr6CoEz+GZKUurJf8HUlGBIeaUNwJTgkMxLge7CscYZdr1ZEZhU1AycaQj+QpUwwt9j2snw7btr3EApSOeei4ZUJ9qpnG9UEy/yQ01kQGoY3a+2yyBMhmhGquo=}
